# Generated by Django 5.1 on 2024-09-02 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('expected_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_hours', models.CharField(max_length=50)),
                ('cv_file', models.FileField(upload_to='cv_files/')),
                ('qualifications', models.TextField()),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pages.job')),
            ],
        ),
    ]
