# Generated by Django 5.1 on 2024-09-02 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('education', models.CharField(max_length=255)),
                ('institution_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('student', 'Student')], max_length=20)),
                ('course_name', models.CharField(max_length=255)),
                ('previous_experience', models.TextField()),
                ('learned_about_course', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='pages.course')),
            ],
        ),
    ]
