# Generated by Django 5.1 on 2024-09-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_courseapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='learned_about_course',
            field=models.CharField(choices=[('friend', 'Friend'), ('socialmedia', 'Social media'), ('website', 'Website'), ('advertisements', 'Advertisements'), ('other', 'Other')], max_length=20),
        ),
    ]
