# Generated by Django 5.1 on 2024-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements_images/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
