# Generated by Django 5.1 on 2024-09-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
