# Generated by Django 5.1.1 on 2024-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_achievements_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duties_responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time')], default='fulltime', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.CharField(default='5-6 Years', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='role_overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='seniority_level',
            field=models.CharField(default='Entry Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='6 October, Giza', max_length=255),
        ),
    ]
