# Generated by Django 5.1.1 on 2024-09-10 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority_level',
            field=models.CharField(max_length=50),
        ),
    ]
