# Generated by Django 5.1 on 2025-01-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_achievements_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseapplication',
            name='course',
        ),
        migrations.AddField(
            model_name='achievements',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='og_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='achievements',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='achievements',
            name='og_type',
            field=models.CharField(default='article', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='og_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo_images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='og_type',
            field=models.CharField(default='article', max_length=50),
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='CourseApplication',
        ),
    ]
